/*
 * Swagger WeRec - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WeRecWebApp.Repository;
using WeRecWebApp.Services;


namespace WeRecWebApp.Apis
{
    /// <summary>
    /// 
    /// </summary>
    [Route("api/v1/videos")]
    public class VideoApiController : Controller
    {
        private readonly IFeedRepository _repo;
        private readonly YTVideoService _videoService;
        public VideoApiController(IFeedRepository repo, YTVideoService videoService)
        {
            _repo = repo;
            _videoService = videoService;
        }

        /// <summary>
        /// Get videos
        /// </summary>
        /// <remarks>Returns an array of video links</remarks>
        /// <param name="feedId">ID of feed</param>
        /// <param name="keyword">keyword</param>
        /// <response code="200">Returns list of video links</response>
        /// <response code="400">Invalid feed id or keyword supplied</response>
        /// <response code="404">Feed or keyword not found</response>
        [HttpGet("{feedId}/{keyword}/")]
        public async Task<IActionResult> GetVideosByFeedId([FromRoute] [Required] string feedId, [FromRoute] [Required] string keyword)
        {
            var feed = await _repo.GetFeed(feedId);
            if (feed == null) return NotFound();

            var videos = await _videoService.GetVideos(feed, keyword);
            return Ok(videos);
        }
    }
}
