/*
 * WeRec Authorization service
 *
 * This is specification of WeRec authorization service. Source code is found on [Github repository](https://github.com/hse-wasd-team/werec). 
 *
 * API version: 1.0.0
 * Contact: syutsydypova@edu.hse.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {

	Id int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`
}
