/*
 * Swagger WeRec - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WeRecWebApp.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class PutFeedModel
    {
        /// <summary>
        /// Gets or Sets Configurations
        /// </summary>

        [DataMember(Name = "configurations")]
        public List<FeedConfiguration> Configurations { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>

        [DataMember(Name = "tags")]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>

        [DataMember(Name = "description")]
        public string Description { get; set; }

        /// <summary>
        /// visibility of the feed
        /// </summary>
        /// <value>visibility of the feed</value>

        [DataMember(Name = "visibility")]
        public VisibilityEnum? Visibility { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>

        [DataMember(Name = "name")]
        public string Name { get; set; }

    }
}
